### ISSUE TITLE
Adding new light problems

### ISSUE THREAD

**Issue by CalebKendra** [term-world/traffic-circle-solution#7]
Suggesting that we add more traffic lights such as 
* If a crosswalk button was pressed then the light could change
* * such as if crosswalk = True, light = Yellow, then red
* If one side of the traffic was busy and another side was not busy then we have the user use conditional statements to have one side change to be green and the other red

**Comment by dluman** [comment]
Take care to:

```bash
ln -s ../.flags .flags
```

in each new directory, too.
